package com.example.calcalc.data

import android.content.Context
import com.google.firebase.FirebaseApp

/**
 * `google-services.json` is deliberately not in the repo, so the app must be able to boot
 * without it and explain what is missing instead of crashing on first Firebase call.
 */
object FirebaseConfig {

    fun isConfigured(context: Context): Boolean =
        FirebaseApp.getApps(context).isNotEmpty() && webClientId(context) != null

    /**
     * `default_web_client_id` is generated by the Google Services plugin. Looked up by name
     * rather than through `R.string` so the project still compiles before Firebase is set up.
     */
    fun webClientId(context: Context): String? {
        val id = context.resources.getIdentifier(
            "default_web_client_id", "string", context.packageName
        )
        return if (id == 0) null else context.getString(id)
    }
}
